### PR TITLE
Add more materials for Czech (cs)

### PR DESCRIPTION
**Pull request by MikkCZ**
Changes:
- moved README.md to general.md + updated headline
- added new README.md with links to various materials currently out of this repository

### CODE REVIEW

**Comment by MikkCZ** [comment]
@unclenachoduh should I ask someone from the team for a review, even if the text content in the repository is without changes?

**Comment by unclenachoduh** [comment]
@MikkCZ yes. Any time you make a change, make a PR and ask for a review from l10n-drivers. Although many contributors are very good with GitHub, we want to make sure those who are less so can get help and a review along the way. I hope it's not too much to ask of you :)

**Comment by MikkCZ** [comment]
No problem, I actually meant a peer review from our l10n team.

I understand the pros of PRs and I am happy with having them merged by the l10n-drivers. Also this is my first experience with gitbook, so I appreciate you have checked the changes. :)

**Comment by unclenachoduh** [comment]
Oh, that is a great idea. If you want to have someone from the team review the merged style guide, you can make a new PR if there are any changes needed. 

In the future, the drivers might ask for a review before merging PRs. That's a good call.

**Pull request merged**
