### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by upwinxp**
corrected image display & removed incorrect tip & corrections

### CODE REVIEW

**Comment by flodolo** [comment]
Hi Lan, does this needs to be reviewed by someone else in the Slovenian team?

P.S. it's a good idea to add your real name to the GitHub profile, it took me a moment to connect the dots ;-)

**Comment by upwinxp** [comment]
Hi Flod!
Regarding the guideline I have removed - I first asked Matjaž to remove it, and he asked me to create an account and do it myself, so I guess he's okay with it.
Thanks for the tip - Github is something new to me :-) I'll add a name.
Lan

**Comment by flodolo** [comment]
OK, let's merge then. Thanks for the PR!

(cc @mathjazz)

**Comment by mathjazz** [comment]
Nice work, @upwinxp! Thanks for merging, Flod!

**Pull request merged**
