### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by rowdymehul**
Added styleguides file for Gujarati language. will complete the guidelines by this week.

### CODE REVIEW

**Comment by MikkCZ** [comment]
Hi @rowdymehul .
Since you opened the PR, the guidelines for new style guides have been consolidated (see https://mozilla-l10n.github.io/styleguides/guidelines/). The outline and example style guide are updated too. If you need any help with creating the style guide, feel free to get in touch. :)

**Comment by rowdymehul** [comment]
Hi @MikkCZ, 

Thanks for the update. Will check and ping you if need any help.

**Comment by flodolo** [comment]
@rowdymehul 

What's the status of this PR? We noticed it's still open, and we should either close it or merge it.

**Comment by flodolo** [comment]
Correction: updated or closed. Right now the folder is in the wrong path, and pages need to be added to SUMMARY.md

**Comment by flodolo** [comment]
At this point, I'm going to close this one. Feel free to reopen.

**Pull request closed without merging**
