### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ravi103151**
Updated Terminology in out Hindi style guide

### CODE REVIEW

**Comment by ravi103151** [comment]
Updated Terminology in out Hindi style guide

**Comment by gueroJeff** [comment]
Travis reports the following errors:

/home/travis/build/mozilla-l10n/styleguides/docs/hi-IN/README.md: 126: no-trailing-spaces Trailing spaces

/home/travis/build/mozilla-l10n/styleguides/docs/hi-IN/README.md: 131: no-multiple-blanks Multiple consecutive blank lines

/home/travis/build/mozilla-l10n/styleguides/docs/hi-IN/README.md: 123: blanks-around-headers Headers should be surrounded by blank lines

@ravi103151 Please correct and resubmit.

**Comment by gueroJeff** [comment]
Hi @ravi103151 Please address the Travis issues: 

/home/travis/build/mozilla-l10n/styleguides/docs/hi-IN/README.md: 126: no-trailing-spaces Trailing spaces

/home/travis/build/mozilla-l10n/styleguides/docs/hi-IN/README.md: 131: no-multiple-blanks Multiple consecutive blank lines

/home/travis/build/mozilla-l10n/styleguides/docs/hi-IN/README.md: 123: blanks-around-headers Headers should be surrounded by blank lines

If you have questions, please ask.

**Comment by ravi103151** [comment]
Same has been updated in #152 request hence closing this branch

**Pull request closed without merging**
