### PR TITLE
Use Travis CI for gh-pages deploy

### PR DESCRIPTION
**Pull request by MikkCZ**
https://docs.travis-ci.com/user/deployment/pages/

alternative to #95

For some reason the deploy is failing for me, even with a dummy repository. :( I have contacted Travis CI support and will see, what's wrong.

### CODE REVIEW

**Comment by flodolo** [comment]
This looks promising. Let's keep #95 on hold, let me know if I should try testing on my own branch.

**Comment by MikkCZ** [comment]
I have been notified by the support it was cause by https://github.com/travis-ci/travis-ci/issues/9312, which is now resolved and it works now.

[Here](https://travis-ci.org/MikkCZ/styleguides/builds/352689817) is the build I tested today and the [commit in gh-pages](https://github.com/MikkCZ/styleguides/commits/gh-pages) branch it produced. I suggest to test on your on fork before merging into master to have the token ready etc. It should be enough to [give the token `public_repo` scope only](https://screenshots.firefox.com/UpFuysqhJvtbmS4g/github.com).

**Comment by flodolo** [comment]
So, I tried on my fork and it works.
* ([commit](https://github.com/flodolo/styleguides/commit/05b902960f059a450528af756cf5021e0ac31740).
* [Travis build](https://travis-ci.org/flodolo/styleguides/builds/352774170).
* [deployment on gh-pages](https://github.com/flodolo/styleguides/commit/98cef9474baa4d2fd5896abafb894ab5043edc61).

I think we should close #95, and document what's needed for setting up automation (create token, add it to Travis-ci and which name to use for the env variable).

**Comment by MikkCZ** [comment]
Yes. Let's close the other PR.

Do we need some extra documentation than what's in Travis CI docs, or just
summerize it in few steps in README and link to that docs for more info? As
we can probably use this for all the Gitbook repos, the l10n-drivers
documentation may be actually mlre appropriate place to put it in, than
README files in each repo.

--
Michal Stanke

Dne 13. 3. 2018 11:48 dopoledne napsal uživatel "Francesco Lodolo" <
notifications@github.com>:

**Comment by flodolo** [comment]
> As we can probably use this for all the Gitbook repos, the l10n-drivers documentation may be actually mlre appropriate place to put it in, than README files in each repo.

You have a point. Let me set up a different token for this repo and merge.

**Pull request merged**
