### PR TITLE
Add style guide for locale id

### PR DESCRIPTION
**Pull request by peiying2**
- Per community request, help move the style guide from community team page to style guide repo: https://wiki.mozilla.org/L10n:Teams:id/Style_Guide.

### CODE REVIEW

**Comment by peiying2** [comment]
I will ping Fauzan to check on content accuracy.

**Comment by flodolo** [comment]
(I kind of remember Jeff saying that he would be up for reviews for this repo, but I might be also imagining things)

**Comment by peiying2** [comment]
> (I kind of remember Jeff saying that he would be up for reviews for this repo, but I might be also imagining things)

Sorry flod, :(. I wonder if I run into the same issue last time when I couldn't pass travis check.

**Comment by flodolo** [comment]
> Sorry flod, :(. I wonder if I run into the same issue last time when I couldn't pass travis check.

The only errors reported are actual errors (remove trailing spaces), nothing related to the infrastructure.

**Comment by gueroJeff** [comment]
I'm happy to review once checks are passing.

**Comment by peiying2** [comment]
Thanks flod for the rescue (Again!). @gueroJeff officially ready for review.

**Comment by flodolo** [comment]
This added the l10n-linter folder, and I missed it :-\

I'm going to remove it directly from master.

**Pull request merged**
