### PR TITLE
New Czech styleguide

### PR DESCRIPTION
**Pull request by MikkCZ**
**me (@MikkCZ) squash this before merge!**

In this iteration (here) I would like to fill the example outline. Later I want to follow with adding more information from the task we have (https://github.com/MozillaCZ/ukoly/issues/14) and get inspired from existing style guides we have on out list.

### CODE REVIEW

**Comment by MikkCZ** [comment]
It's ready for the first wave of feedback from other community members and global Czech @l10ncz community.

@gueroJeff @unclenachoduh are you interested in looking at it too, if it's something you expected?

**Comment by gueroJeff** [comment]
I've been following along. It looks great! :-) Very detailed

**Comment by flodolo** [comment]
@MikkCZ 
Ignore the Travis failures, those are (partially) @gueroJeff fault, and they should be fixed :) 🐻

**Comment by gueroJeff** [comment]
@flodolo oh no, what'd I do now? :-\

**Comment by flodolo** [comment]
> @flodolo oh no, what'd I do now? :-\

This one (es-MX) had failures. I've fixed them, but this one will keeps failing unless rebased against master.

But don't worry, you were in good company (@vesper-mozilla, pl-sumo). ;-)
Those errors were fixed by a contributor.

**Comment by gueroJeff** [comment]
Interesting, cause I only merged and squashed because there were no
failures reported by Travis. Weird.

**Comment by MikkCZ** [comment]
So far I have got only positive reviews, no requests for change. Let's wait after the coming weekend and merge it if nothing appears.

**Comment by MikkCZ** [comment]
No requests for changes -> let's merge it.

**Pull request merged**
