### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by train255**

### CODE REVIEW

**Comment by flodolo** [comment]
Let me know when it's ready to merge, or if you need anyone else in your team to review it

**Comment by MikkCZ** [comment]
@train255 Are these changes final? If so, please rebase the changes, so we can merge it (or let me know and I can probably rebase it for you). In the meantime we have moved the file in the repository - that's why GitHub shows conflict.

**Comment by train255** [comment]
Sorry, I haven't finished it. We will have to rewrite our style guide based on [the guidelines](https://github.com/mozilla-l10n/styleguides/tree/master/docs/guidelines)

**Comment by flodolo** [comment]
@train255 
Unfortunately this PR became stale and would need a rebase, which is not trivial from GitHub. Can you please resubmit your changes in a new PR?

**Pull request closed without merging**
